### ISSUE TITLE
No longer works since 2 may

### ISSUE THREAD

**Issue by Lucus123** [costastf/toonapilib#11] opened 2018-05-04 22:02 UTC
Apilib constantly errors out on HA 0.68.1
I use it with python 3.6.
Below is error trace
Log Details (ERROR)

Fri May 04 2018 23:51:59 GMT+0200 (CEST)

Error during setup of component toonTraceback (most recent call last): File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component component.setup, hass, processed_config) File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__ yield self # This tells Task to wait for completion. File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup future.result() File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result raise self._exception File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/home/homeassistant/.homeassistant/custom_components/toon.py", line 69, in setup config['toon'][CONF_NAME]) File "/home/homeassistant/.homeassistant/custom_components/toon.py", line 107, in __init__ display_common_name=name) File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 100, in __init__ self._authenticate() File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 147, in _authenticate self._get_agreements() File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 168, in _get_agreements for agreement in agreements] File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py", line 168, in <listcomp> for agreement in agreements] AttributeError: 'str' object has no attribute 'get'

**Comment by costastf** [comment] 2018-05-05 10:59
I am sorry, I cannot reproduce this. Is there any chance your subscription to eneco has expired?

**Comment by costastf** [comment] 2018-05-05 11:07
Could you please try out this branch https://github.com/costastf/toonapilib/tree/b-no-agreement that handles that so we can troubleshoot and maybe fix this for you? Please be careful what you paste though in case there is any sensitive information there. Thanks!

**Comment by Lucus123** [comment] 2018-05-14 19:47
i have no experience using github, i dont know how to install from this
repository on a hassbian setup

2018-05-05 13:07 GMT+02:00 Costas <notifications@github.com>:

**Comment by costastf** [comment] 2018-05-24 20:00
I have created a new 3.0.2 version with a handle of your error so we can debug further. Please update the version of the library in the HA component and report back when you have something new.

**Comment by Lucus123** [comment] 2018-05-24 21:05
i installed the new version, everything seems to be working again as it
should!

2018-05-24 22:00 GMT+02:00 Costas <notifications@github.com>:

**Comment by Lucus123** [comment] 2018-05-24 21:11
it seems i was too early, none of the controls that should be controlling
the thermostat temperature or the selector that changes the programs the
thermostat runs, are working, the call gets sent fron hassbian but nothing
happens on the device

2018-05-24 23:05 GMT+02:00 luuk neele <ljj.neele@gmail.com>:

**Comment by costastf** [comment] 2018-05-26 10:40
The latest version does not have any fix for any issue, it just extends the error handling in order to see why you are getting that exception. Please try out the library outside of the context of Home Assistant and let me know if you have any issue using it independently.

**Comment by kootenpv** [comment] 2018-05-28 17:03
Reading the state works, but setting it doesn't.

I try:

    toon.thermostat = 25

and that doesn't work. The next time I ask for `toon.thermostat` it has the old value. Also on Toon I cannot see any difference. Any idea how come?

**Comment by costastf** [comment] 2018-05-28 17:07
Could you please try with debugging enabled and report back? That should shed some light. 
To enable debugging please 
import logging
Iogging.basicConfig(level= logging.DEBUG)

**Comment by kootenpv** [comment] 2018-05-28 19:40
Thanks for the reply!

Here it is:

```python
DEBUG:toonapilib.Toon:Using patched request for url https://api.toon.eu//toon/v3/494995/thermostat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.toon.eu
DEBUG:urllib3.connectionpool:https://api.toon.eu:443 "GET //toon/v3/494995/thermostat HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.toon.eu
DEBUG:urllib3.connectionpool:https://api.toon.eu:443 "PUT //toon/v3/494995/thermostat HTTP/1.1" 200 None
DEBUG:toonapilib.Toon:Response received b'{\n  "currentSetpoint" : 2500,\n  "currentDisplayTemp" : 2700,\n  "programState" : 1,\n  "activeState" : -1,\n  "nextProgram" : 1,\n  "nextState" : 2,\n  "nextTime" : 1527541200,\n  "nextSetpoint" : 1500,\n  "errorFound" : 255,\n  "boilerModuleConnected" : 1,\n  "realSetpoint" : 2000,\n  "burnerInfo" : "0",\n  "otCommError" : "0",\n  "currentModulationLevel" : 0,\n  "haveOTBoiler" : 1\n}'
DEBUG:toonapilib.Toon:Clearing state cache.
DEBUG:toonapilib.Toon:Using patched request for url https://api.toon.eu//toon/v3/494995/status
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.toon.eu
DEBUG:urllib3.connectionpool:https://api.toon.eu:443 "GET //toon/v3/494995/status HTTP/1.1" 200 None
DEBUG:toonapilib.Toon:Using patched request for url https://api.toon.eu//toon/v3/494995/status
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.toon.eu
DEBUG:urllib3.connectionpool:https://api.toon.eu:443 "GET //toon/v3/494995/status HTTP/1.1" 200 None
```

After all those (regardless how long I wait): 

    print(toon.thermostat)
    20.0
     
And the Toon display still shows `20.0` as well.

Looking in the documentation, it shows that `realSetpoint != currentSetPoint`. What could that even mean?

**Comment by costastf** [comment] 2018-05-28 20:01
Well,I don't see any issue sadly. The response is ok and there is no error raised. There is a "errorFound" flag on the response which means that server side something went wrong but there is not much we can do with the data we have.

**Comment by kootenpv** [comment] 2018-05-28 20:03
In your other thread the same problem was raised.

When you look online you can indeed see that `realSetpoint` is the one that should be changed. The package currently is only setting `currentSetpoint`. Also, the page shows that error code 255 means "OK" (strange code, but it is NOT a server side error).

Quoting from https://developer.toon.eu/api-intro:

    "realSetpoint": 1050, // The setpoint that is really active based on the program or manual setting
    "currentSetpoint": 1050, // Current target temperature for the thermostat 
    "errorFound": 255, // 255 means everything ok. Anything else means there is trouble

**Comment by costastf** [comment] 2018-05-28 20:07
http://developer.toon.eu/toonapi/apis/put/%7BagreementId%7D/thermostat has no mention of realSetpoint

**Comment by costastf** [comment] 2018-05-28 20:18
On the page you are quoting it mentions "Setting the thermostat" but mentions everything but that. I don't see any usage for realSetpoint and don't really know how to proceed from this. Especially with ""errorFound": 255, // 255 means everything ok. Anything else means there is trouble " in mind, it seems that the response you get is ok, so not really sure why it does not work for you... Is this the only instance that you are running? Could it be that there is anything competing with the api?

**Comment by kootenpv** [comment] 2018-05-28 20:53
Yea, it is weird right? Well, I don't have any API running. But I do have the Toon app installed. It is not using the same credentials. Do you think that one is conflicting? I doubt that uninstalling the app would have an effect. Preferably, I would have both working.

**Comment by costastf** [comment] 2018-05-28 21:00
Nah, the app should be fine.

**Comment by Lucus123** [comment] 2018-05-28 21:19
hi,

how do i use the toonapilib outside of homeassistant?
i think id need a piece of software capable of making api calls? (which
home assistant is)
i am not a developer, i have no idea how to replicate what you're asking me
to do.
i receive no more errors, and all states are again read correctly, i can
also switch on/off my fibaro plugs connected to toon.
i can however, not set the thermostat. this does not work at all, i can set
it, but it does not change on the device.




2018-05-26 12:40 GMT+02:00 Costas <notifications@github.com>:

**Comment by Lucus123** [comment] 2018-05-28 21:22
i appear to have the same issue as pascal, no data is set on the device
through homeassistant.

2018-05-28 23:00 GMT+02:00 Costas <notifications@github.com>:

**Comment by kootenpv** [comment] 2018-05-28 22:29
I have sent an email to the developers, I'll update when I hear from them.

**Comment by costastf** [comment] 2018-05-29 06:12
@Lucus123 please follow the installation and usage pages of the documentation at http://toonapilib.readthedocs.io/en/latest/

**Comment by scheric** [comment] 2018-05-29 16:09
It  works again. 🎉  Using HA 0.70.
I can change the temperature of the thermostat and i am getting data of power usage.

**Comment by Lucus123** [comment] 2018-05-29 17:22
Does not work for me, i get all data, can controle fibaro switches etc but
cannot set thermostat. Data Just does not seem te pass to the device

**Comment by costastf** [comment] 2018-05-29 19:50
@Lucus123 have you tried working directly with the library?

**Comment by costastf** [comment] 2018-05-31 15:46
Is there any way that you have two eneco subscriptions?

**Comment by kootenpv** [comment] 2018-05-31 18:00
I don't think so?

I was able to make a change once from the Toon swagger, not exactly sure what I filled in, but the `realSetpoint` did change. I think I submitted the returned data of toonapilib with a change to it (don't remember if it was realSetpoint or currentSetpoint), and then it did change. I think that's the only time I was able to make a change.

**Comment by costastf** [comment] 2018-06-01 11:02
Please try to reboot your toon, I can't think of anything else that might be of an issue.

**Comment by Lucus123** [comment] 2018-06-05 20:49
Hi,

I think I found something. It appears that toonapilib has a problem with
the toon thermostat being in Dutch. See below error:

Log Details (ERROR)

Tue Jun 05 2018 22:38:24 GMT+0200 (CEST)

Error executing service <ServiceCall climate.set_operation_mode:
operation_mode=eco, entity_id=['climate.toon']>

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py",
line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py",
line 393, in async_operation_set_service
    await climate.async_set_operation_mode(operation_mode)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/toon.py",
line 107, in set_operation_mode
    self.thermos.set_state(toonlib_values[operation_mode])
  File "/home/homeassistant/.homeassistant/custom_components/toon.py",
line 174, in set_state
    self.toon.thermostat_state = state
  File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py",
line 446, in thermostat_state
    self._validate_thermostat_state_name(name)
  File "/srv/homeassistant/lib/python3.6/site-packages/toonapilib/toonapilib.py",
line 425, in _validate_thermostat_state_name
    raise InvalidThermostatState(name)
toonapilib.toonapilibexceptions.InvalidThermostatState: Weg


Op vr 1 jun. 2018 13:02 schreef Costas <notifications@github.com>:

**Comment by scheric** [comment] 2018-06-05 21:15
Do you know if you changed anything in the toonapilib. 

When I changed something in the toonapilib and I break some stuff i found an easy fix to get everything back to normal. 

Make a copy of the toonapilib folder to be safe!
Try deleting folder `/srv/homeassistant/lib/python3.6/site-packages/toonapilib/` to get a fresh install of toonapilib. 

*You have to reboot after deletion of the toonapilib folder.
After the reboot you can check if the folder is back. *

**Comment by Lucus123** [comment] 2018-06-05 21:31
Not changed anything.
Completely original.

Op di 5 jun. 2018 23:15 schreef scheric <notifications@github.com>:

**Comment by scheric** [comment] 2018-06-05 21:36
@Lucus123 

Did you change something in the custom_components folder?

Have you tried to refresh the toonapilib as described?
If there is a change in github without an version change the toonapilib probably does not update.

**Comment by scheric** [comment] 2018-06-05 22:10
@Lucus123 
Ore you can turn the debugging mode on by replacing all `logger.debug` to `logger.warning` in **toonapilib.py** 

> I did this myself and saw `Manually set temperature, no Thermostat State chosen!`

If this happens everything should be fine but report if you see something different.

look for `Response received` and check if `activeState" : X,` changes.

**Comment by costastf** [comment] 2018-07-07 11:51
Hi @Lucus123. Sorry it took so long for me to answer, but I was on vacation and I needed some time away :) . The exception that you mention happens because the state that is sent to the library to be set on the service is not valid. If you look into the configuration.py of the project you will notice the states mentioned being : 

```STATES = {0: 'Comfort',
          1: 'Home',
          2: 'Sleep',
          3: 'Away',
          4: 'Unknown',
          5: 'Unknown'}```

That means that you have some setting on HA that sends over states in dutch which does not work according to the above mentioned setting. Seeing as that you are the only one affected by this I would guess that this is a setting that you have set and it is not HA specific. Could you please look into your configuration better? Could you also  test the library independent of HA and report back if it works?

**Comment by costastf** [comment] 2018-07-22 10:56
Since this is caused by some custom change I am closing this. If there is more feedback and we can troubleshoot further, lets reopen.

**Closed as completed by costastf** 2018-07-22 10:56 UTC
